name: Android CI

on:
  push:
  pull_request:
    branches: [ zen-launcher ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Google Services config
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets-for-download
        path: app/build/outputs
